# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build Node

on:
  pull_request:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '*.md'
      - '*.yml'
      - '*.txt'

jobs:
  build-node:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ServerProject-DONT-IMPORT-INTO-UNITY
    - name: Build
      run: dotnet build --no-restore
      working-directory: ServerProject-DONT-IMPORT-INTO-UNITY
    - name: Upload LRM
      uses: actions/upload-artifact@v4
      with:
        name: LRM-Node
        path: |
          ServerProject-DONT-IMPORT-INTO-UNITY/MultiCompiled/bin/Debug/net8.0/LRM.dll
          ServerProject-DONT-IMPORT-INTO-UNITY/MultiCompiled/bin/Debug/net8.0/LRM.runtimeconfig.json
          ServerProject-DONT-IMPORT-INTO-UNITY/MultiCompiled/bin/Debug/net8.0/MultiCompiled.dll
